name: Deploying changes to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy-everything:
    name: Deploying changes to staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ssh_key
          chmod 600 ssh_key

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@3.87.96.136 << EOF
            set -e  # Stop on error

            cd ~/turbo-test/BookMyShow/

            echo "✅ Pulling latest changes..."
            git pull origin main

            echo "🔧 Ensuring pnpm is installed..."
            if ! command -v pnpm >/dev/null 2>&1; then
              curl -fsSL https://get.pnpm.io/install.sh | sh -
              export PATH="\$HOME/.local/share/pnpm:\$PATH"
              echo 'export PATH="\$HOME/.local/share/pnpm:\$PATH"' >> ~/.bashrc
            fi

            export PATH="\$HOME/.local/share/pnpm:\$PATH"

            echo "📦 Installing dependencies..."
            pnpm install

            echo "🔨 Building the project..."
            pnpm run build

            echo "🚀 Restarting PM2..."
            if ! command -v pm2 >/dev/null 2>&1; then
              npm install -g pm2
            fi

            pm2 restart all
          EOF
